import { type ClassValue, clsx } from 'clsx';
import { twMerge } from 'tailwind-merge';

export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs));
}

// Node metadata with colors and icons
import type { NodeMetadata, NodeType } from '../types/workflow';

export const nodeMetadata: Record<NodeType, NodeMetadata> = {
  ACTION: {
    type: 'ACTION',
    label: 'Action',
    description: 'Perform simple built-in actions',
    category: 'action',
    icon: 'Zap',
    color: '#8B5CF6',
  },
  AI_AGENT: {
    type: 'AI_AGENT',
    label: 'AI Agent',
    description: 'Execute a conversational AI agent',
    category: 'agent',
    icon: 'Bot',
    color: '#3B82F6',
  },
  HTTP: {
    type: 'HTTP',
    label: 'HTTP Request',
    description: 'Make HTTP requests to external services',
    category: 'integration',
    icon: 'Globe',
    color: '#10B981',
  },
  CONDITION: {
    type: 'CONDITION',
    label: 'Condition',
    description: 'Conditional routing based on data',
    category: 'logic',
    icon: 'GitBranch',
    color: '#F59E0B',
  },
  TRANSFORM: {
    type: 'TRANSFORM',
    label: 'Transform',
    description: 'Reshape or remap data',
    category: 'data',
    icon: 'Shuffle',
    color: '#6366F1',
  },
  FILTER: {
    type: 'FILTER',
    label: 'Filter',
    description: 'Filter arrays based on conditions',
    category: 'data',
    icon: 'Filter',
    color: '#8B5CF6',
  },
  LOOP: {
    type: 'LOOP',
    label: 'Loop',
    description: 'Iterate over array items',
    category: 'logic',
    icon: 'Repeat',
    color: '#EC4899',
  },
  SWITCH: {
    type: 'SWITCH',
    label: 'Switch',
    description: 'Route to different branches',
    category: 'logic',
    icon: 'Split',
    color: '#F59E0B',
  },
  DELAY: {
    type: 'DELAY',
    label: 'Delay',
    description: 'Pause workflow execution',
    category: 'action',
    icon: 'Clock',
    color: '#6B7280',
  },
  EMAIL: {
    type: 'EMAIL',
    label: 'Email',
    description: 'Send emails',
    category: 'communication',
    icon: 'Mail',
    color: '#EF4444',
  },
  SEND_MESSAGE: {
    type: 'SEND_MESSAGE',
    label: 'Send Message',
    description: 'Send messages through channels',
    category: 'communication',
    icon: 'MessageSquare',
    color: '#10B981',
  },
  SQL: {
    type: 'SQL',
    label: 'SQL',
    description: 'Execute SQL queries',
    category: 'data',
    icon: 'Database',
    color: '#3B82F6',
  },
  SUB_WORKFLOW: {
    type: 'SUB_WORKFLOW',
    label: 'Sub-Workflow',
    description: 'Execute another workflow',
    category: 'logic',
    icon: 'Workflow',
    color: '#8B5CF6',
  },
  HTTP_RESPONSE: {
    type: 'HTTP_RESPONSE',
    label: 'HTTP Response',
    description: 'Send HTTP response',
    category: 'integration',
    icon: 'Send',
    color: '#10B981',
  },
  BUFFER: {
    type: 'BUFFER',
    label: 'Buffer',
    description: 'Collect and batch messages',
    category: 'data',
    icon: 'Inbox',
    color: '#6366F1',
  },
  MERGE: {
    type: 'MERGE',
    label: 'Merge',
    description: 'Combine data from multiple nodes',
    category: 'data',
    icon: 'Merge',
    color: '#8B5CF6',
  },
  ERROR_HANDLER: {
    type: 'ERROR_HANDLER',
    label: 'Error Handler',
    description: 'Handle errors from previous nodes',
    category: 'logic',
    icon: 'AlertTriangle',
    color: '#EF4444',
  },
  VALIDATE: {
    type: 'VALIDATE',
    label: 'Validate',
    description: 'Validate data against schema',
    category: 'data',
    icon: 'CheckCircle',
    color: '#10B981',
  },
  WEBHOOK_WAIT: {
    type: 'WEBHOOK_WAIT',
    label: 'Webhook Wait',
    description: 'Wait for webhook to resume',
    category: 'action',
    icon: 'Pause',
    color: '#6B7280',
  },
  SPEECH_TO_TEXT: {
    type: 'SPEECH_TO_TEXT',
    label: 'Speech-to-Text',
    description: 'Transcribe audio to text',
    category: 'integration',
    icon: 'Mic',
    color: '#3B82F6',
  },
  TEXT_TO_SPEECH: {
    type: 'TEXT_TO_SPEECH',
    label: 'Text-to-Speech',
    description: 'Convert text to speech',
    category: 'integration',
    icon: 'Volume2',
    color: '#8B5CF6',
  },
  VIDEO_GENERATION: {
    type: 'VIDEO_GENERATION',
    label: 'Video Generation',
    description: 'Generate videos from prompts',
    category: 'integration',
    icon: 'Video',
    color: '#EC4899',
  },
  NANO_BANANA: {
    type: 'NANO_BANANA',
    label: 'Image Generation',
    description: 'Generate images with AI',
    category: 'integration',
    icon: 'Image',
    color: '#F59E0B',
  },
  CLOUD_STORAGE: {
    type: 'CLOUD_STORAGE',
    label: 'Cloud Storage',
    description: 'Interact with cloud storage',
    category: 'integration',
    icon: 'Cloud',
    color: '#3B82F6',
  },
  FILE_STORAGE: {
    type: 'FILE_STORAGE',
    label: 'File Storage',
    description: 'Manage files in storage',
    category: 'integration',
    icon: 'FolderOpen',
    color: '#6366F1',
  },
  HUBSPOT: {
    type: 'HUBSPOT',
    label: 'HubSpot',
    description: 'Integrate with HubSpot CRM',
    category: 'integration',
    icon: 'Users',
    color: '#FF7A59',
  },
  AGENT_ADD_MESSAGE: {
    type: 'AGENT_ADD_MESSAGE',
    label: 'Add Message',
    description: 'Add message to conversation',
    category: 'agent',
    icon: 'MessageCircle',
    color: '#3B82F6',
  },
  AGENT_CLEANUP_SESSIONS: {
    type: 'AGENT_CLEANUP_SESSIONS',
    label: 'Cleanup Sessions',
    description: 'Clean up inactive sessions',
    category: 'agent',
    icon: 'Trash2',
    color: '#EF4444',
  },
  AGENT_CLEAR_MEMORY: {
    type: 'AGENT_CLEAR_MEMORY',
    label: 'Clear Memory',
    description: 'Clear conversation memory',
    category: 'agent',
    icon: 'Eraser',
    color: '#6B7280',
  },
  AGENT_CREATE_SESSION: {
    type: 'AGENT_CREATE_SESSION',
    label: 'Create Session',
    description: 'Create conversation session',
    category: 'agent',
    icon: 'Plus',
    color: '#10B981',
  },
  AGENT_DELETE_MESSAGES: {
    type: 'AGENT_DELETE_MESSAGES',
    label: 'Delete Messages',
    description: 'Delete session messages',
    category: 'agent',
    icon: 'X',
    color: '#EF4444',
  },
  AGENT_GET_MESSAGES: {
    type: 'AGENT_GET_MESSAGES',
    label: 'Get Messages',
    description: 'Retrieve conversation history',
    category: 'agent',
    icon: 'List',
    color: '#3B82F6',
  },
  AGENT_MESSAGE_STATS: {
    type: 'AGENT_MESSAGE_STATS',
    label: 'Message Stats',
    description: 'Get conversation statistics',
    category: 'agent',
    icon: 'BarChart',
    color: '#6366F1',
  },
  AGENT_UPDATE_SESSION_CONTEXT: {
    type: 'AGENT_UPDATE_SESSION_CONTEXT',
    label: 'Update Context',
    description: 'Update session context',
    category: 'agent',
    icon: 'Edit',
    color: '#8B5CF6',
  },
};

// Group nodes by category
export const nodesByCategory = Object.values(nodeMetadata).reduce(
  (acc, node) => {
    if (!acc[node.category]) {
      acc[node.category] = [];
    }
    acc[node.category].push(node);
    return acc;
  },
  {} as Record<string, NodeMetadata[]>
);
